#!/usr/bin/perl

#
# (C) Copyright 1998 HotDiary Inc.
#
# Software is confidential copyrighted information of HotDiary and
# title to all copies is retained by HotDiary and/or its licensors.
# Licensee shall not modify, decompile, disassemble, decrypt, extract,
# or otherwise. Software may not be leased, assigned, or sublicensed,
# in whole or in part.
#

#
# FileName: proctrans.cgi
# Purpose: process transactions
# Creation Date: 09-11-99
# Created by: Smitha Gudur
#

require "cgi-lib.pl";
use ParseTem::ParseTem;
use tparser::tparser;
use AsciiDB::TagFile;            
use utils::utils;

# Read in all the variables set by the form
   &ReadParse(*input);


   ## URL Manager section of the settings menu. x_ADC_URL field.
   ## 1. x_response_code (1 = Approved, 2 = Declined, 3=Error)
   ## 2. x_response_subcode = A code used by the system for internal
   ##    transaction tracking
   ## 3. x_response_reason_code = A Code giving more details about the the 
   ## transaction
   ## 4. x_response_reason_text = Brief description of result, which corresponds
   ##                  with the Response Reason Code 
   ## 5. x_auth_code = 6 digit approval code
   ## 6. x_avs_code = Indicates the result of Address Verification System (AVS)
   ##  checks.
   ##                        A = Address (Street) matches, ZIP does
   ##                        not
   ##                        E = AVS error
   ##                        N = No Match on Address (Street) or ZIP
   ##                        P = AVS not applicable for this
   ##                        transaction
   ##                        R = Retry - System unavailable or timed
   ##                        out
   ##                        S = Service not supported by issuer
   ##                        U = Address information is unavailable
   ##                        W = 9 digit ZIP matches, Address
   ##                        (Street) does not
   ##                        X = Exact AVS Match
   ##                        Y = Address (Street) and 5 digit ZIP
   ##                        match
   ##                        Z = 5 digit ZIP matches, Address
   ##                        (Street) does not
   ## 7. x_trans_id = This number identifies the transaction
   ##                        in the system, and can be used to submit
   ##                        a modification of this transaction at a
   ##                        later time via HTML form POST (such as
   ##                        voiding the transaction, or capturing an Auth only
   ##    transaction

   ## list of the input values are echoed
   ## 8.x_invoice_num, 9. x_description,  10. x_amount, 11. x_method
   ## 12. x_type, 13. x_cust_id, 14. x_first_name, 15. x_last_name,
   ## 16. x_company, 17. x_address, 18. x_city, 19. x_state, 20. x_zip
   ## 21. x_country, 22. x_phone, 23. x_fax, 24. x_email, 25. x_ship_to_first_name
   ## 26. x_ship_to_last_name, 27. x_ship_to_company, 28. x_ship_to_address
   ## 29. x_ship_to_city, 30. x_ship_to_state, 31. x_ship_to_zip,
   ## 32. x_ship_to_country, 33. x_tax,  34. x_duty, 35. x_freight, 36. x_tax_exempt

   ## 37. x_po_num, 38. x_md5_hash, 39. any other our fields defined. 

   ## x_md5_hash = generated by the system and to be validated by merchant 
   ##     for added security


   ## https://secure.authorize.net/gateway/transact.dll 
   ## x_ADC_Relay_Response - This field must be in the form and set to a value 
   ## 
   ## of TRUE to tell the system that it will be doing an ADC Relay Response 
   ## transaction. 

   ## x_ADC_URL - The value of this field is the URL to which the system will 
   ## return the results of the transaction. The results of the transaction 
   ## will be returned via a HTTP form POST to the specified URL. As an extra 
   ## security 
   ## precaution, the URL specified in this field must be a Valid ADC or Receipt 
   ##  Link URL, as specified in the URL Manager. 

   ## values that are defaulted are:
   ## x_Bank_Acct_Type=CHECKING (if this is not passed.
   ## x_Color_Background=#FFFFFF (white)
   ## x_Color_Link=Blue or #0000FF
   ## x_Color_Text= Black or #000000
   ## x_Email_Customer=TRUE
   ## x_Email_Merchant=TRUE
   ## x_Receipt_Link_Method=LINK
   ## x_Receipt_Link_Text=Continue (any string can be specified)
   ## x_Tax_Exempt=False

  #(https://secure.authorize.net/gateway.transact.dll?X_ADC_Relay_Response=TRUE&x_ADC_Delim_Data=$comma&x_address=$address&x_amount=$amount&x_Card_Num=$cardnumber&x_ADC_URL=http://www.hotdiary.com/processtransaction.cgi?

  $invoicenum = $input{x_invoice_num};
  hddebug "invoicenum = $invoicenum";

  $avscode = $input{x_avs_code};
  hddebug "avscode = $avscode";
  if ( ($avscode ne "X") && ($avscode ne "Y") ) {
  #if ($avscode ne "X") {
     status "Your personal information is not a correct match with reference to your credit card. Please go <a href=http://www.hotdiary.com>back to the original page</a>, and enter the correct credit card information. Invoice number is $invoicenum.";
     exit;
  }
  

  $response = $input{x_response_code};
  hddebug "response = $response";

  $reason_code = $input{x_response_reason_code};
  hddebug "response_reason_code = $reason_code";
  $reason_text = $input{x_response_reason_text};
  hddebug "response_reason_text = $reason_text";

  $fname = $input{x_first_name};
  hddebug "fname = $fname";

  $lname = $input{x_last_name};
  hddebug "lname = $lname";

  #$street = $input{x_street_name};
  #hddebug "street = $street";

  $street = $input{x_address};
  hddebug "street = $street";

  $city = $input{x_city};
  hddebug "city = $city";

  $state = $input{x_state};
  hddebug "state = $state";

  $zipcode = $input{x_zip};
  hddebug "zipcode = $zipcode";

  ## this cannot be accessed because of security reasons.
  ## this can be accessed only from https://secure.authorize.net form
  ##$cardnum = $input{x_card_num};
  ##hddebug "cardnum = $cardnum";

  $email = $input{x_email};
  hddebug "email = $email";


  $fax = $input{x_fax};
  hddebug "fax = $fax";

  $product_type = $input{x_description};
  $login = $input{x_cust_id};
  $password = $input{password};

  hddebug "login = $login";
  hddebug "pasword = $password";
  hddebug "product_type = $product_type";


  $alphaindex = substr $login, 0, 1;
  $alphaindex = $alphaindex . '-index';



  #if ($product_type eq "wordit") {
     #system "echo '#!/bin/ksh' > $ENV{HDHOME}/tmp/wordit$$-$login";
     #$worditparms = "login=$login&password=$password";
     #$cgis = "$ENV{HDEXECCGI}/execworddownload.cgi";
     #system "echo \"$cgis\" \"$worditparms\" >> $ENV{HDHOME}/tmp/wordit$$-$login";
     #exit;
  #}

  ## it means not approved
  if ($reason_code != 1) {
     status("$reason_text. Please complete the form and press Submit Transaction Button");
     exit;
  }

  # bind prodtab table vars
   tie %prodtab, 'AsciiDB::TagFile',
   DIRECTORY => "$ENV{HDDATA}/prodtab",
   SUFIX => '.rec',
   SCHEMA => {
   ORDER => ['entryno', 'prodtitle', 'prodprice', 'proddesc', 'filelink' ] };

  $product_exists = 0;
  foreach $rec (keys %prodtab) {
     if ($prodtab{$rec}{prodtitle} eq $product_type) {
	 $product_exists = 1;
	 $filelink = $prodtab{$rec}{filelink};
	 last;    
     }
  }

  if ($reason_code == 1) {
     if (($product_type eq "WordIt") || 
        ($product_type eq "JiveIt! Portal Builder For Commercial Sites") || 
	($product_type eq "Community Event") ||
	($product_type eq "JazzIt! Portal Software") ||
	($product_type eq "Quadruple Traffic To Your Site") ||
	($product_type eq "Press Release To NewsDiary") || 
	($product_exists == 1) ) {

        # bind login table vars
        tie %ordertab, 'AsciiDB::TagFile',
        DIRECTORY => "$ENV{HDDATA}/aux/ordertab",
        SUFIX => '.rec',
        SCHEMA => {
             ORDER => ['invoicenum', 'login', 'fname', 
		'lname', 'company', 'street', 'city', 'state', 
		'zipcode', 'country', 'email', 'prodtype', 'amount'] };

       
         $invoicenum = $input{x_invoice_num};
         $company = $input{x_company};
         $country = $input{x_country};
         $amount = $input{x_amount};

         $ordertab{$invoicenum}{invoicenum} = $invoicenum;
         $ordertab{$invoicenum}{login} = $login;
         $ordertab{$invoicenum}{fname} = $fname;
         $ordertab{$invoicenum}{lname} = $lname;
         $ordertab{$invoicenum}{company} = $company;
         $ordertab{$invoicenum}{street} = $street;
         $ordertab{$invoicenum}{city} = $city;
         $ordertab{$invoicenum}{state} = $state;
         $ordertab{$invoicenum}{zipcode} = $zipcode;
         $ordertab{$invoicenum}{country} = $country;
         $ordertab{$invoicenum}{email} = $email;
         $ordertab{$invoicenum}{prodtype} = $product_type;
         $ordertab{$invoicenum}{amount} = $amount;
         tied(%ordertab)->sync();

         if ($product_type eq "WordIt") {
            system "mkdir -p $ENV{HTTPHOME}/html/hd/words/key-$$";
            system "ln -s $ENV{HDHOME}/yp/WordIt20.zip $ENV{HTTPHOME}/html/hd/words/key-$$";
            system "ln -s $ENV{HDHOME}/yp/WordIt20.txt $ENV{HTTPHOME}/html/hd/words/key-$$";
            system "$ENV{HDEXECCGI}/execcleanwordit $ENV{HTTPHOME}/html/hd/words/key-$$/WordIt20.zip";
            system "$ENV{HDEXECCGI}/execcleanwordit $ENV{HTTPHOME}/html/hd/words/key-$$/WordIt20.txt";

          status("$login: Your credit card has been approved. Congratulations! HotDiary's WordIt! English Diary is ready. Please click <a href=\"http://www.hotdiary.com/words/key-$$/WordIt20.zip\">here to download the diary</a>. <p>If you have problems downloading above file, click <a href=\"http://www.hotdiary.com/words/key-$$/WordIt20.txt\">here</a> to download the alternate file.<p>You have 15 minutes to download the diary. It will not be available for download at the end of 15 minutes. <p><i>If for some reason, you are not able to download the diary, please <a href=\"http://www.hotdiary.com/contact_us.html\">contact us</a> and we will be glad to help you.");
         exit;
	}

        if ($product_exists == 1 ) {
	    $filename = qx{basename $filelink};
	    if ($filename eq "") {
               if ($product_type eq 'JiveIt! ASP Software') {
                  status("$login: Your credit card has been approved. Please click <a href=\"http://www.hotdiary.com/jiveitprofauth.html\">here</a> to proceed with the setup of $product_type.");
                  exit;
               } else {
                 if ($product_type eq 'Business LetterHead') {
                    status("$login: Your credit card has been approved. Please click <a href=\"http://www.hotdiary.com/jsp/eletterhead.jsp?invoicenum=$invoicenum&login=$login\">here</a> to proceed with the creation of $product_type.");
                    exit;
                 }
               }
		status("$login: Your credit card has been approved. HotDiary will contact you shortly as long as your email address was specified.");
		exit; 
	    }
            $filename =~ s/\r//g;
            $filename =~ s/\n//g;
            system "mkdir -p $ENV{HTTPHOME}/html/hd/products/key-$$";
            system "ln -s $filelink $ENV{HTTPHOME}/html/hd/products/key-$$";
            system "$ENV{HDEXECCGI}/execcleanproduct $ENV{HTTPHOME}/html/hd/products/key-$$";

          status("$login: Your credit card has been approved. Congratulations! HotDiary's $product_type software is ready. Please click <a href=\"http://www.hotdiary.com/products/key-$$/$filename\">here to download the product</a>. You have 15 minutes to download the product. It will not be available for download at the end of 15 minutes. <p><i>If for some reason, you are not able to download the product, please <a href=\"http://www.hotdiary.com/contact_us.html\">contact us</a> and we will be glad to help you.");
         exit;
	}
        

        if ($product_type eq "JiveIt! Portal Builder For Commercial Sites") {
           $prml = "";
           $prml = strapp $prml, "login=$login";
           $prml = strapp $prml, "password=$password";
           $prml = strapp $prml, "template=$ENV{HDTMPL}/jiveitprofauth.html";
           $prml = strapp $prml, "templateout=$ENV{HDREP}/$alphaindex/$login/jiveitauth-$$.html";
           $prml = strapp $prml, "welcome=Welcome";
           parseIt $prml;

           $prml = "";
           $prml = strapp $prml, "template=$ENV{HDTMPL}/redirect_url_expiry.html";
           $prml = strapp $prml, "templateout=$ENV{HDHREP}/$alphaindex/$login/redirect_url_jiveitauth-$$.html";
           $prml = strapp $prml, "redirecturl=http://www.hotdiary.com/rep/$alphaindex/$login/jiveitauth-$$.html";
           parseIt $prml;
           system "/bin/cat $ENV{HDTMPL}/content.html";
           system "/bin/cat $ENV{HDHREP}/$alphaindex/$login/redirect_url_jiveitauth-$$.html";
           exit;
        }

	if ($product_type eq "JazzIt! Portal Software") {
           $prml = "";
           $prml = strapp $prml, "login=$login";
           $prml = strapp $prml, "password=$password";
           $prml = strapp $prml, "template=$ENV{HDTMPL}/jazzitauth.html";
           $prml = strapp $prml, "templateout=$ENV{HDREP}/$alphaindex/$login/jazzitauth-$$.html";
           parseIt $prml;

           $prml = "";
           $prml = strapp $prml, "template=$ENV{HDTMPL}/redirect_url_expiry.html";
           $prml = strapp $prml, "templateout=$ENV{HDHREP}/$alphaindex/$login/redirect_url_jazzittauth-$$.html";
           $prml = strapp $prml, "redirecturl=http://www.hotdiary.com/rep/$alphaindex/$login/jazzitauth-$$.html";
           parseIt $prml;
           system "/bin/cat $ENV{HDTMPL}/content.html";
           system "/bin/cat $ENV{HDHREP}/$alphaindex/$login/redirect_url_jazzitauth-$$.html";
           exit;
        }

        if ($product_type eq "Community Event") {
           $prml = "";
           $prml = strapp $prml, "login=$login";
           $prml = strapp $prml, "template=$ENV{HDTMPL}/comeventsadd_new.html";
           $prml = strapp $prml, "templateout=$ENV{HDHREP}/$alphaindex/$login/comeventsadd_new-$$.html";
           parseIt $prml;
           system "/bin/cat $ENV{HDTMPL}/content.html";
           system "/bin/cat $ENV{HDHREP}/$alphaindex/$login/comeventsadd_new-$$.html";
           exit;
        }


	if ($product_type eq "Press Release To NewsDiary") {
           $prml = "";
           $prml = strapp $prml, "login=$login";
           $prml = strapp $prml, "template=$ENV{HDTMPL}/submitpressrelease.html";
           $prml = strapp $prml, "templateout=$ENV{HDHREP}/$alphaindex/$login/submitpressrelease-$$.html";
           parseIt $prml;
           system "/bin/cat $ENV{HDTMPL}/content.html";
           system "/bin/cat $ENV{HDHREP}/$alphaindex/$login/submitpressrelease-$$.html";
	   exit;
	}

	if ($product_type eq "Quadruple Traffic To Your Site") {
           $prml = "";
           $prml = strapp $prml, "login=$login";
           $prml = strapp $prml, "template=$ENV{HDTMPL}/quadtraffic.html";
           $prml = strapp $prml, "templateout=$ENV{HDHREP}/$alphaindex/$login/quadtraffic-$$.html";
           parseIt $prml;
           system "/bin/cat $ENV{HDTMPL}/content.html";
           system "/bin/cat $ENV{HDHREP}/$alphaindex/$login/quadtraffic-$$.html";
	   exit;
        }
       
     }

     if ($product_type eq "My Downtown - B2B Planner") {
	 $business = $input{x_ship_to_company};

	 tie %downtowntab, 'AsciiDB::TagFile',
         DIRECTORY => "$ENV{HDDATA}/aux/downtowntab",
         SUFIX => '.rec',
         SCHEMA => {
            ORDER => ['login', 'fname', 'lname', 'company', 
                'street', 'city', 'state', 'zipcode',
                'country', 'email', 'prodtype', 'amount', 'invoicenum',
	        'business'] };

         $invoicenum = $input{x_invoice_num};
         $company = $input{x_company};
         $country = $input{x_country};
         $amount = $input{x_amount};

         $downtowntab{$login}{invoicenum} = $invoicenum;
         $downtowntab{$login}{login} = $login;
         $downtowntab{$login}{fname} = $fname;
         $downtowntab{$login}{lname} = $lname;
         $downtowntab{$login}{company} = $company;
         $downtowntab{$login}{street} = $street;
         $downtowntab{$login}{city} = $city;
         $downtowntab{$login}{state} = $state;
         $downtowntab{$login}{zipcode} = $zipcode;
         $downtowntab{$login}{country} = $country;
         $downtowntab{$login}{email} = $email;
         $downtowntab{$login}{prodtype} = $product_type;
         $downtowntab{$login}{amount} = $amount;
         tied(%downtowntab)->sync();
 
         status("$login: Your credit card has been approved. Congratulations! for joining the growing number of B2B Businesses. Now you can use software services of B2B Planner.");
          exit;
        }
    }

    $msg = "<DL><LI>Download WordIt!</LI><LI>Use JiveIt! Portal Builder For Commercial Sites</LI><LI>Access B2B Business Planner</LI><LI>Submit Your Press Release to NewsDiary</LI></DL>";
    $msg = adjusturl $msg;

    if ($reason_code == 1) {
       status("$login: If you have received this message and not able to download the WordIt! product or use JiveIt! Portal Builder For Commercial Sites, or not able to access B2B Business Planner, send us an email at hotdiary\@hodiary.com");
       exit;
    } 
