copy execdologin.cgi c:\"program files"\"apache group"\apache\cgi-bin\calendar\execdologin.cgi
copy execdologin.cgi c:\"program files"\"apache group"\apache\cgi-bin\calendar\execdocalclient.cgi
copy execdologin.cgi c:\"program files"\"apache group"\apache\cgi-bin\calendar\execcalclient.cgi
copy execdologin.cgi c:\"program files"\"apache group"\apache\cgi-bin\calendar\execregister.cgi
copy execdologin.cgi c:\"program files"\"apache group"\apache\cgi-bin\calendar\execdoprofile.cgi
copy execdologin.cgi c:\"program files"\"apache group"\apache\cgi-bin\calendar\execdoprofupdate.cgi
copy execdologin.cgi c:\"program files"\"apache group"\apache\cgi-bin\calendar\execaccessprivatecal.cgi
copy execdologin.cgi c:\"program files"\"apache group"\apache\cgi-bin\calendar\execeditsubscribegroupcal.cgi
copy execdologin.cgi c:\"program files"\"apache group"\apache\cgi-bin\calendar\execcreateprivatecal.cgi
copy execdologin.cgi c:\"program files"\"apache group"\apache\cgi-bin\calendar\execmanagegroupcal.cgi
copy execdologin.cgi c:\"program files"\"apache group"\apache\cgi-bin\calendar\execgroupcal.cgi
copy execdologin.cgi c:\"program files"\"apache group"\apache\cgi-bin\calendar\execupdategroupcal.cgi
copy execdologin.cgi c:\"program files"\"apache group"\apache\cgi-bin\calendar\execsubscribeprivatecal.cgi
copy execdologin.cgi c:\"program files"\"apache group"\apache\cgi-bin\calendar\execsearchgroupcal.cgi
copy execdologin.cgi c:\"program files"\"apache group"\apache\cgi-bin\calendar\execeditprivatecal.cgi
	